name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  website:
    name: Website Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: website/node_modules
          key: ${{ runner.os }}-node-website-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-website-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./website

      - name: Build Astro site
        run: yarn build
        working-directory: ./website

  dashboard-frontend:
    name: Dashboard Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: dashboard/frontend/node_modules
          key: ${{ runner.os }}-node-frontend-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-frontend-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./dashboard/frontend

      - name: Run ESLint
        run: yarn lint
        working-directory: ./dashboard/frontend

      - name: Run frontend tests
        run: yarn test
        working-directory: ./dashboard/frontend

      - name: Build dashboard
        run: yarn build
        working-directory: ./dashboard/frontend

  python:
    name: Python Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dashboard/backend/requirements.txt
          pip install pyright pytest

      - name: Run Pyright
        run: pyright

      - name: Run Bot Tests
        run: pytest tests/

      - name: Run Backend Tests
        run: pytest dashboard/backend/tests/