name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Node.js projects
        run: |
          # ESLint with GitHub annotation format
          yarn lint --format eslint-formatter-github
        continue-on-error: true

      - name: Run Node.js tests
        run: |
          # Vitest with GitHub reporter
          yarn test --reporter=github-actions
        continue-on-error: true

      - name: Build Node.js projects
        run: |
          # Vite build with error formatting
          yarn build 2>&1 | while IFS= read -r line; do
            if [[ "$line" =~ error|Error|ERROR ]]; then
              echo "::error::Build Error: $line"
            elif [[ "$line" =~ warning|Warning|WARNING ]]; then
              echo "::warning::Build Warning: $line"
            else
              echo "$line"
            fi
          done
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt -r dashboard/backend/requirements.txt pyright pytest ruff

      - name: Run Ruff
        run: |
          # Ruff already configured with --output-format=github
          ruff check bot.py cogs/ dashboard/backend --output-format=github
        continue-on-error: true

      - name: Run Pyright
        run: |
          # Pyright with GitHub annotation format
          pyright --outputjson 2>&1 | python -c "
          import json
          import sys
          try:
              data = json.load(sys.stdin)
              for diagnostic in data.get('generalDiagnostics', []):
                  file_path = diagnostic.get('file', 'unknown')
                  line = diagnostic.get('range', {}).get('start', {}).get('line', 0) + 1
                  col = diagnostic.get('range', {}).get('start', {}).get('character', 0) + 1
                  severity = diagnostic.get('severity', 'error').lower()
                  message = diagnostic.get('message', 'Unknown error')
                  
                  if severity == 'error':
                      print(f'::error file={file_path},line={line},col={col}::{message}')
                  elif severity == 'warning':
                      print(f'::warning file={file_path},line={line},col={col}::{message}')
                  else:
                      print(f'::notice file={file_path},line={line},col={col}::{message}')
          except:
              # Fallback to regular pyright output
              import subprocess
              subprocess.run(['pyright'], check=False)
          "
        continue-on-error: true

      - name: Run Python Tests
        run: |
          # Pytest with GitHub annotation integration
          pytest --tb=short -v 2>&1 | python -c "
          import sys
          import re
          
          for line in sys.stdin:
              line = line.strip()
              # Match pytest FAILED lines
              failed_match = re.match(r'FAILED (.*?)::(.*?) - (.*)', line)
              if failed_match:
                  file_path, test_name, error = failed_match.groups()
                  print(f'::error file={file_path}::Test Failed: {test_name} - {error}')
              # Match pytest ERROR lines
              elif 'ERROR' in line and '::' in line:
                  error_match = re.match(r'ERROR (.*?)::(.*?) - (.*)', line)
                  if error_match:
                      file_path, test_name, error = error_match.groups()
                      print(f'::error file={file_path}::Test Error: {test_name} - {error}')
              # Match assertion errors or other test failures
              elif re.match(r'.*\.py:\d+:', line):
                  parts = line.split(':', 2)
                  if len(parts) >= 3:
                      file_path = parts[0]
                      line_num = parts[1]
                      message = parts[2].strip()
                      print(f'::error file={file_path},line={line_num}::{message}')
              else:
                  print(line)
          "
        continue-on-error: true

      - name: Check for failures
        run: |
          echo "::notice::All checks completed. Review annotations above for any issues."
          # You can add logic here to fail the workflow if critical issues are found
          # For example, check if specific files exist or parse previous outputs

  changes:
    name: "Detect Changes"
    needs: build_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      website: ${{ steps.filter.outputs.website }}
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      bot: ${{ steps.filter.outputs.bot }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Filter changed paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            website:
              - 'website/**'
            frontend:
              - 'dashboard/frontend/**'
            backend:
              - 'dashboard/backend/**'
            bot:
              - 'bot.py'
              - 'cogs/**'
              - 'database/**'
              - 'requirements.txt'

  deploy-website:
    name: "Deploy Website"
    needs: changes
    if: needs.changes.outputs.website == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.sha }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Website
        run: yarn build

      - name: Install Wrangler
        run: yarn global add wrangler

      - name: Deploy Website
        run: wrangler deploy
        working-directory: ./website
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: production

  deploy-dashboard-frontend:
    name: "Deploy Dashboard Frontend"
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: frontend-prod
          ref: ${{ github.sha }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Dashboard Frontend
        run: yarn build
        env:
          VITE_DISCORD_CLIENT_ID: ${{ vars.VITE_DISCORD_CLIENT_ID }}

      - name: Install Wrangler
        run: yarn global add wrangler

      - name: Deploy Dashboard Frontend
        run: wrangler deploy
        working-directory: ./dashboard/frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: frontend-prod

  deploy-dashboard-backend:
    name: "Deploy Dashboard Backend"
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      statuses: write
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: backend-prod
          ref: ${{ github.sha }}

      - name: Deploy Dashboard Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/discordbot/openguard
            git pull origin main
            sudo /home/discordbot/openguard/scripts/deploy_backend.sh

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: backend-prod

  deploy-bot:
    name: "Deploy Bot"
    needs: changes
    if: needs.changes.outputs.bot == 'true'
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      statuses: write
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: bot-prod
          ref: ${{ github.sha }}

      - name: Deploy Discord Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/discordbot/openguard
            git pull origin main
            /home/discordbot/.pyenv/versions/3.11.2/bin/python -m pip install -r requirements.txt
            sudo systemctl restart openguard-bot.service

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: bot-prod