name: Deploy to Production

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:
    inputs:
      website:
        description: 'Deploy Website'
        required: false
        type: boolean
      frontend:
        description: 'Deploy Dashboard Frontend'
        required: false
        type: boolean
      backend:
        description: 'Deploy Dashboard Backend'
        required: false
        type: boolean
      bot:
        description: 'Deploy Bot'
        required: false
        type: boolean

permissions:
  contents: read
  deployments: write
  statuses: write

jobs:
  changes:
    if: (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      website: ${{ steps.set_outputs.outputs.website }}
      frontend: ${{ steps.set_outputs.outputs.frontend }}
      backend: ${{ steps.set_outputs.outputs.backend }}
      bot: ${{ steps.set_outputs.outputs.bot }}
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_run'
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 2
      - uses: dorny/paths-filter@v2
        if: github.event_name == 'workflow_run'
        id: filter
        with:
          filters: |
            website:
              - 'website/**'
            frontend:
              - 'dashboard/frontend/**'
            backend:
              - 'dashboard/backend/**'
            bot:
              - 'bot.py'
              - 'cogs/**'
              - 'database/**'
              - 'requirements.txt'
      - id: set_outputs
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "website=${{ github.event.inputs.website }}" >> $GITHUB_OUTPUT
            echo "frontend=${{ github.event.inputs.frontend }}" >> $GITHUB_OUTPUT
            echo "backend=${{ github.event.inputs.backend }}" >> $GITHUB_OUTPUT
            echo "bot=${{ github.event.inputs.bot }}" >> $GITHUB_OUTPUT
          else
            echo "website=${{ steps.filter.outputs.website }}" >> $GITHUB_OUTPUT
            echo "frontend=${{ steps.filter.outputs.frontend }}" >> $GITHUB_OUTPUT
            echo "backend=${{ steps.filter.outputs.backend }}" >> $GITHUB_OUTPUT
            echo "bot=${{ steps.filter.outputs.bot }}" >> $GITHUB_OUTPUT
          fi

  deploy-website:
    needs: changes
    if: ${{ needs.changes.outputs.website == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.sha }}

      - uses: actions/checkout@v4
        with:
          ref: "${{ if(github.event_name == 'workflow_run', github.event.workflow_run.head_sha, github.ref) }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: website/node_modules
          key: ${{ runner.os }}-node-website-${{ hashFiles('website/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-website-

      - name: Install dependencies
        run: npm ci
        working-directory: ./website

      - name: Build Website
        run: npm run build
        working-directory: ./website

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy Website
        run: wrangler deploy
        working-directory: ./website
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Mark Deployment as Successful
        if: success()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          status: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Mark Deployment as Failed
        if: failure()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          status: failure
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  deploy-dashboard-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: frontend-prod
          ref: ${{ github.sha }}

      - uses: actions/checkout@v4
        with:
          ref: "${{ if(github.event_name == 'workflow_run', github.event.workflow_run.head_sha, github.ref) }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: dashboard/frontend/node_modules
          key: ${{ runner.os }}-node-frontend-${{ hashFiles('dashboard/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-frontend-

      - name: Install dependencies
        run: npm ci
        working-directory: ./dashboard/frontend

      - name: Build Dashboard Frontend
        run: npm run build
        working-directory: ./dashboard/frontend
        env:
          VITE_DISCORD_CLIENT_ID: ${{ vars.VITE_DISCORD_CLIENT_ID }}

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy Dashboard Frontend
        run: wrangler deploy
        working-directory: ./dashboard/frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Mark Deployment as Successful
        if: success()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: frontend-prod
          status: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Mark Deployment as Failed
        if: failure()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: frontend-prod
          status: failure
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  deploy-dashboard-backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: backend-prod
          ref: ${{ github.sha }}

      - name: Deploy Dashboard Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/discordbot/openguard
            git pull origin main
            sudo /home/discordbot/openguard/scripts/deploy_backend.sh

      - name: Mark Deployment as Successful
        if: success()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: backend-prod
          status: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  deploy-bot:
    needs: changes
    if: ${{ needs.changes.outputs.bot == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: bot-prod
          ref: ${{ github.sha }}

      - name: Deploy Discord Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/discordbot/openguard
            git pull origin main
            /home/discordbot/.pyenv/versions/3.11.2/bin/python -m pip install -r requirements.txt
            sudo systemctl restart openguard-bot.service

      - name: Mark Deployment as Successful
        if: success()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: bot-prod
          status: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Mark Deployment as Failed
        if: failure()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: bot-prod
          status: failure
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

