name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./dashboard/frontend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./dashboard/frontend
      - name: Build Dashboard Frontend
        run: npm run build
        working-directory: ./dashboard/frontend
      - name: Run Frontend Tests
        run: npm run test
        working-directory: ./dashboard/frontend

  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyright
      - name: Run Pyright
        run: pyright