name: Python Tests

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'bot.py'
      - 'cogs/**'
      - 'tests/**'
      - 'dashboard/backend/**'
      - 'database/**'
      - 'pyrightconfig.json'
      - 'requirements.txt'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'bot.py'
      - 'cogs/**'
      - 'tests/**'
      - 'dashboard/backend/**'
      - 'database/**'
      - 'pyrightconfig.json'
      - 'requirements.txt'

jobs:
  bot_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Bot Tests
        run: pytest tests/

  backend_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: pip install -r requirements.txt
        working-directory: ./dashboard/backend
      - name: Run Backend Tests
        run: pytest tests/
        working-directory: ./dashboard/backend